// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8UufoGIgrt6pJfeu6eFMOkv7WXzfvqg',
    appId: '1:712968994762:web:d708c60d017affbab69933',
    messagingSenderId: '712968994762',
    projectId: 'fir-para-flutter-fc257',
    authDomain: 'fir-para-flutter-fc257.firebaseapp.com',
    storageBucket: 'fir-para-flutter-fc257.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDbIvskJz1Qo4LgxjS6AiPmumOD6rXcbM',
    appId: '1:712968994762:android:f3425a864577e912b69933',
    messagingSenderId: '712968994762',
    projectId: 'fir-para-flutter-fc257',
    storageBucket: 'fir-para-flutter-fc257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcKhZyH-S8ZAeUCe1kf-VrOkVCZkdubiQ',
    appId: '1:712968994762:ios:db026bb19d270caab69933',
    messagingSenderId: '712968994762',
    projectId: 'fir-para-flutter-fc257',
    storageBucket: 'fir-para-flutter-fc257.appspot.com',
    iosClientId: '712968994762-ph7ae8povk54qqa15rqg7k7g4m4ecd3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcKhZyH-S8ZAeUCe1kf-VrOkVCZkdubiQ',
    appId: '1:712968994762:ios:db026bb19d270caab69933',
    messagingSenderId: '712968994762',
    projectId: 'fir-para-flutter-fc257',
    storageBucket: 'fir-para-flutter-fc257.appspot.com',
    iosClientId: '712968994762-ph7ae8povk54qqa15rqg7k7g4m4ecd3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
